### ISSUE TITLE
대댓글 생성 및 게시글 삭제 시 댓글, 대댓글 연쇄삭제(cascade 설정)

### ISSUE THREAD

**Issue by leebuwon** [picnee/picnee_back#26]
### 🌱 만들고자 하는 기능

- 대댓글 생성과 게시글이 삭제 될 경우 댓글과 대댓글이 연쇄삭제 되야합니다. 저희 서비스는 softDelete가 적영되어 있어 어떻게 연쇄삭제할지 고민을 해봐야겠습니다. (수동으로 update를 처주는 방향으로 구현할 것 같습니다.)
- 댓글을 삭제할 경우 대댓글도 같이 삭제할지 대댓글은 보여줄 지 고민해봐야할 것 같습니다. (의논 후 진행)

### 🌱 구현 내용

- [x] 대댓글 생성
- [ ] 게시글 삭제 시 댓글 연쇄 삭제
- [ ] 댓글 삭제 시 대댓글 연쇄 삭제

### 🕐 예상 기간

- 2024.11.09 ~ 2024.11.10

**Comment by tkdtn4657** [comment]
공유해주신 이슈 관련해서 고민 해보았을 때
댓글, 대댓글 간의 연관관계 설정으로 게시글에서 PostCommentRepository 없이 제거가 가능할 것으로 보이는 상황을 제안드리려합니다.

**AS-IS**

- 현재 Post, PostComment 엔티티의 양방향 연관관계 설정으로 Post 자체에서 PostComment를 불러오지 못하는 상황

**Post.java**

```java

    ......

    @OneToMany(mappedBy = "post")
    private List<PostComment> comments = new ArrayList<>();

    ......

```

**PostComment.java**

```java

    ......

    @ManyToOne(fetch = LAZY)
    @JoinColumn(name = "post_id")
    private Post post;

    ......

```

**TO-BE**

- PostComment는 Post엔티티의 `post_id` 외에는 Post컬럼이 필요하지 않음
- Post와, PostComment를 서로 참조하고있는 양방향 의존관계에서 - Post가 PostComment만을 바라보는 단방향 의존관계로 참조하도록 변경
**Post.java**

```java

    ......

    @OneToMany
    @JoinColumn(name = "post_id")  // 이 부분을 추가하여 post_id 외래 키가 post_comment 테이블에 생성되도록 합니다.
    private List<PostComment> comments = new ArrayList<>();

    ......

```

**PostComment.java**

```java

    ......

    // 외래 키는 'Post' 엔티티에서 관리하므로 'post' 필드가 필요 없음
    //private Post post;

    //필요하다면 private UUID postId;
    형태로 관리할 수 있음

    ......

```

이에 대해서 직접 테스트를 해보고싶은데, 금일 저녁 이후로 가능할 것 같습니다
